import { writeFile } from 'node:fs/promises';

const baseUrl = 'https://api.betacalendars.com';
const monthNames = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const slugs = monthNames.map((month) => month.toLowerCase());
const refUrl = (month) => `https://www.betacalendars.com/${month.toLowerCase()}-calendar.html`;
const script = (checks = []) => ({
  type: 'text/javascript',
  exec: [
    'pm.test("status is 200", () => pm.response.to.have.status(200));',
    'pm.test("response is JSON", () => pm.expect(pm.response.headers.get("Content-Type")).to.include("application/json"));',
    'const body = pm.response.json();',
    ...checks,
  ],
});
const responseExample = (name, request, body, code = 200) => ({
  name, originalRequest: structuredClone(request), status: code === 200 ? 'OK' : 'Bad Request', code,
  _postman_previewlanguage: 'json', header: [{ key: 'Content-Type', value: 'application/json; charset=utf-8' }],
  cookie: [], body: `${JSON.stringify(body, null, 2)}\n`,
});
function request(name, path, description, checks = [], example = undefined, exampleCode = 200) {
  const req = { method: 'GET', header: [{ key: 'Accept', value: 'application/json' }], url: { raw: `{{baseUrl}}${path}`, host: ['{{baseUrl}}'], path: path.split('?')[0].split('/').filter(Boolean), query: (path.split('?')[1] ?? '').split('&').filter(Boolean).map((part) => { const [key, ...rest] = part.split('='); return { key, value: rest.join('='), description: key }; }) } };
  return { name, request: req, response: example ? [responseExample(exampleCode === 200 ? 'Successful response' : 'Structured input error', req, example, exampleCode)] : [], event: [{ listen: 'test', script: script(checks) }], description };
}
const health = request('01 Health Check', '/health', 'Confirm the read-only calendar API is reachable. No credentials are required. A successful response identifies only the service and health state.', ['pm.expect(body.status).to.eql("ok");', 'pm.expect(body.service).to.eql("betacalendars-calendar-api");'], { status: 'ok', service: 'betacalendars-calendar-api' });
const jan = request('02 January 2027 Month Grid', '/v1/month/2027/1?weekStart=monday&gridMode=fixed-six-weeks&adjacentDays=include', 'Build January 2027 as a six-row Monday-first grid. January has 31 days; the result has 6 rows and includes December/February adjacent dates.\n\nHuman-readable reference: [January Calendar](' + refUrl('January') + ').', ['pm.expect(body.month).to.eql(1);', 'pm.expect(body.year).to.eql(2027);', 'pm.expect(body.daysInMonth).to.eql(31);', 'pm.expect(body.rowCount).to.eql(6);', 'pm.expect(body.weekStart).to.eql("monday");', 'pm.expect(body.reference.url).to.eql("' + refUrl('January') + '");']);
const printJan = request('03 January 2027 A4 Print Layout', '/v1/print-layout/2027/1?paper=a4&orientation=portrait&weekStart=monday&gridMode=fixed-six-weeks&margin=10&headerHeight=20&weekdayHeaderHeight=10&notesHeight=0', 'Calculate A4 portrait printable bounds and date-cell measurements in millimetres. Values are computed from paper dimensions, margin, header bands, and six calendar rows.', ['pm.expect(body.paper.widthMm).to.eql(210);', 'pm.expect(body.grid.columns).to.eql(7);', 'pm.expect(body.grid.rows).to.eql(6);']);
const blank = request('04 Blank 6x7 Planner', '/v1/blank-grid?rows=6&columns=7&paper=a4&orientation=portrait&margin=10', 'Create a date-free six-by-seven planning grid. Cells carry only row and column coordinates. Use the A4 measurements to plan printing.\n\nHuman-readable resource: [Blank Calendar](https://www.betacalendars.com/blank-calendar).', ['pm.expect(body.rows).to.eql(6);', 'pm.expect(body.columns).to.eql(7);', 'pm.expect(body.cells).to.have.length(6);', 'pm.expect(JSON.stringify(body)).not.to.include("date");']);
const range = request('05 November 2026 to February 2027 Range', '/v1/range?from=2026-11&to=2027-02&weekStart=monday&gridMode=natural', 'Summarize a chronological range inclusive of both endpoint months. This four-month fixture crosses a year boundary; range limits are 120 months.', ['pm.expect(body.count).to.eql(4);', 'pm.expect(body.months.map((m) => `${m.year}-${String(m.month).padStart(2,"0")}`)).to.eql(["2026-11","2026-12","2027-01","2027-02"]);']);
const compare = request('06 Compare Year Boundary', '/v1/compare?months=2026-11,2026-12,2027-01,2027-02&weekStart=monday&gridMode=natural', 'Compare month structure across the 2026 to 2027 boundary without repeating full daily grids.', ['pm.expect(body.months).to.have.length(4);', 'pm.expect(body.differences).to.have.length(4);']);
const year = request('07 2027 Year Summary', '/v1/year/2027?weekStart=monday&gridMode=natural', 'Get compact metadata for all twelve months of 2027 without the repeated day-cell payload.', ['pm.expect(body.year).to.eql(2027);', 'pm.expect(body.isLeapYear).to.eql(false);', 'pm.expect(body.months).to.have.length(12);']);

const overviewDescription = `# BetaCalendars Printable Calendar Geometry API\n\nA deterministic read-only API for Gregorian month grids, printable geometry, blank planning grids, bounded ranges, and calendar topology. It processes no events or personal data.\n\n## Quick start\n\n1. Set collection variable **baseUrl** to the deployed API origin.\n2. Send **01 Health Check**.\n3. Send **02 January 2027 Month Grid** and inspect the returned weeks.\n\nAuthentication: none. All requests are GET-only. Results are timezone-independent.\n\n## Response model\n\nMonth responses identify the Gregorian year/month, month length, first/last weekday, selected week start and grid mode, row count, leading/trailing cells, seven-cell rows, and one contextual canonical reference. Adjacent dates can be included or represented by null placeholders.\n\n## Print geometry\n\nThe print endpoint reports paper dimensions, printable bounds, header regions, grid dimensions, and computed cell area in millimetres. Supported presets are A4, US Letter, A5, and US Legal.\n\n## Calendar topology\n\nUse the year, range, topology, and comparison requests for compact summaries and regression fixtures. Ranges are limited to 120 months. Blank grids are undated and never invent dates.\n\nProject: https://www.betacalendars.com/\n\nBlank planning resource: https://www.betacalendars.com/blank-calendar`;

const folder = (name, item, description = '') => ({ name, description, item });
const monthFixtures = monthNames.map((name, i) => request(`${name} 2027 — Month Grid`, `/v1/month/2027/${i+1}?weekStart=monday&gridMode=fixed-six-weeks&adjacentDays=include`, `January through December fixture for the year 2027. ${name} has a computed ${[31,28,31,30,31,30,31,31,30,31,30,31][i]}-day month and a fixed six-week Monday-first grid. The response contains the canonical month reference: [${name} Calendar](${refUrl(name)}).`, [`pm.expect(body.month).to.eql(${i+1});`, `pm.expect(body.monthName).to.eql("${name}");`, `pm.expect(body.reference.url).to.eql("${refUrl(name)}");` ]));
const errorExample = { error: { code: 'invalid_request', message: 'month must be an integer from 1 to 12' } };
const apiReferenceDescription = `# API Reference\n\nAll endpoints are public, stateless, read-only HTTP GET resources. No API key, cookie, or user account is required. The canonical production base URL is https://api.betacalendars.com. Responses use application/json.\n\nCalendar years are supported from 1 through 9999. The 120-month inclusive range cap keeps responses bounded. Invalid input returns a structured JSON 4xx error.\n\nMonth and layout endpoints compute their values from Gregorian arithmetic; they do not scrape or depend on the human-readable references. The references are static canonical links.\n\nProject: https://www.betacalendars.com/`;
const referenceItems = slugs.map((slug, i) => request(`${monthNames[i]} Reference Resource`, `/v1/references/${slug}`, `Resolve the canonical ${monthNames[i]} printable calendar reference. This request returns metadata only and does not scrape the referenced page.`, [`pm.expect(body.url).to.eql("${refUrl(monthNames[i])}");`]));
const itemList = [
  folder('System', [health]),
  folder('Months', [request('Month Grid', '/v1/month/2027/1?weekStart=monday&gridMode=natural&adjacentDays=include', 'Return a dated Gregorian month model with a configurable first weekday, row mode, and adjacent-day behavior.', ['pm.expect(body.weeks.flat()).to.have.length(body.rowCount * 7);', 'pm.expect(body.weeks.flat().filter((d) => d.kind === "current")).to.have.length(body.daysInMonth);'], { year: 2027, month: 1, monthName: 'January', daysInMonth: 31, firstWeekday: 'friday', lastWeekday: 'sunday', weekStart: 'monday', gridMode: 'natural', rowCount: 6, leadingCellCount: 4, trailingCellCount: 7, weeks: [], reference: { title: 'January Calendar', url: refUrl('January') } })]),
  folder('Years', [year]), folder('Ranges', [range]), folder('Print Layout', [printJan, request('A4 Landscape Layout', '/v1/print-layout/2027/1?paper=a4&orientation=landscape&weekStart=monday&gridMode=fixed-six-weeks', 'A4 landscape geometry. Rotating the sheet exchanges its width and height before margins and date cells are calculated.', ['pm.expect(body.orientation).to.eql("landscape");', 'pm.expect(body.paper.widthMm).to.eql(297);'])]),
  folder('Blank Grids', [blank]), folder('Topology', [request('January 2027 Topology', '/v1/topology/2027/1', 'Expose weekday start, month length, natural row counts for all seven week starts, fixed row count, leading offsets, and stable topology signature.', ['pm.expect(body.fixedRowCount).to.eql(6);', 'pm.expect(body.naturalRowCounts).to.have.property("monday");'])]),
  folder('Comparison', [compare]), folder('Reference Resources', referenceItems.concat([request('Blank Calendar Reference', '/v1/references/blank-calendar', 'Resolve the canonical undated calendar resource. No page is fetched or scraped.', ['pm.expect(body.url).to.eql("https://www.betacalendars.com/blank-calendar");'])])),
  folder('2027 Month Examples', monthFixtures),
];
const errorReq = request('Invalid month — structured 400 example', '/v1/month/2027/13', 'Demonstrate the standard JSON input error shape for an out-of-range month. This intentional example returns HTTP 400.', ['pm.test("invalid month returns 400", () => pm.response.to.have.status(400));', 'pm.expect(body.error.code).to.eql("invalid_request");'], errorExample, 400);
itemList[1].item.push(errorReq);
function collection(name, description, items) {
  return { info: { name, description, schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json' }, item: items, variable: [{ key: 'baseUrl', value: baseUrl, type: 'string' }] };
}
await writeFile(new URL('../postman/BetaCalendars-Getting-Started.postman_collection.json', import.meta.url), JSON.stringify(collection('BetaCalendars API — Getting Started & Examples', overviewDescription, [health, jan, printJan, blank, range, compare, year]), null, 2) + '\n');
await writeFile(new URL('../postman/BetaCalendars-API-Reference.postman_collection.json', import.meta.url), JSON.stringify(collection('BetaCalendars Printable Calendar API Reference', apiReferenceDescription, itemList), null, 2) + '\n');
await writeFile(new URL('../postman/BetaCalendars-Public.postman_environment.json', import.meta.url), JSON.stringify({ name: 'BetaCalendars Public API', values: [{ key: 'baseUrl', value: baseUrl, type: 'default', enabled: true }], _postman_variable_scope: 'environment', _postman_exported_at: new Date().toISOString(), _postman_exported_using: 'Postman/11' }, null, 2) + '\n');
await writeFile(new URL('../postman/README.md', import.meta.url), `# Postman assets\n\nRun \`node scripts/generate-postman.mjs\` to regenerate the two v2.1 collections and the no-secret public environment. The shared \`baseUrl\` points to the intended production host; that hostname is not yet deployed. Never publish saved response examples until they have been captured from the verified production endpoint.\n\nThe collections contain GET requests and Postman tests. The reference collection keeps the twelve 2027 month fixtures in one folder, with each fixture linked only to its corresponding canonical month page.\n`);
